language: python
python:
  - "2.7"
  - "3.7"  
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
  - pip setup.py install
  
# command to run tests
script:
  - pytest
